from .customer import CustomerSerializer
from .ev_station_info import EVStationInfoSerializer
from .ev_station_slot import EVStationSlotSerializer
from .ev_schedule_slot import EVScheduleSlotSerializer