# Generated by Django 3.2.11 on 2022-01-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evslocator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evstationsslot',
            name='end_hours',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evstationsslot',
            name='start_hours',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
