# Generated by Django 3.2.11 on 2022-01-15 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evslocator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_name', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EVAreas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('city_id', models.IntegerField()),
                ('state_id', models.IntegerField()),
                ('area_id', models.IntegerField()),
                ('area_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EVCities',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('city_id', models.IntegerField()),
                ('state_id', models.IntegerField()),
                ('city_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EVScheduleSlot',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('free_from', models.DateTimeField(auto_now_add=True)),
                ('free_to', models.DateTimeField(default=datetime.datetime(2022, 1, 15, 14, 17, 46, 355360))),
                ('payment_mode', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ev_schedule_slot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EVStates',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('state_id', models.IntegerField()),
                ('state_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'states',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EVStationInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('ev_station_name', models.CharField(max_length=255)),
                ('ev_address', models.CharField(max_length=255)),
                ('rating', models.SmallIntegerField(default=0)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('area_code', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ev_station_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EVStationsSlot',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_occupied', models.BooleanField(default=True)),
                ('charges_per_hour', models.FloatField(default=0)),
                ('start_hours', models.TimeField(blank=True)),
                ('end_hours', models.TimeField(blank=True)),
                ('is_available_24_hours', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ev_station_slot',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
