# Generated by Django 3.2.11 on 2022-01-15 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evslocator', '0002_auto_20220115_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='evareas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='evcities',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='evscheduleslot',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='evstates',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='evstationinfo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='evstationsslot',
            options={'managed': True},
        ),
    ]
